## Introduction to Numpy

In [ ]:
# import library
import numpy as np


### Creating an Array

In [ ]:
# creating array zero
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
# creating array 1
np.ones(3)


array([1., 1., 1.])

In [ ]:
# creating array using range with step
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
# creating array which how many number between start and end number
np.linspace(1, 100, 11)

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [ ]:
# creating array from list
a = np.array([1, 2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [ ]:
# aceessing array and also change the value
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

### Multidimensional Array

In [ ]:
# creatting array zero using function with dim 5 x 2 
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# creating array from list
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# accsessing array row
n[2]

array([7, 8, 9])

In [ ]:
# change array value based on row and column
n[0,1] = 10
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
# change array row
n[2] = [1,1,1]
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [32]:
# acessing array column and change the value
n[:, 2] = [1,2,3]
n

array([[ 1, 10,  1],
       [ 4,  5,  2],
       [ 1,  1,  3]])

### random generated array

In [ ]:
# random array with dim 5 x 2 
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [36]:
# random array with dim 5 x 2 with normal distribution
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [ ]:
# random array with dim 5 x 2 with integer number
np.random.seed(2)
np.random.randint(low=1, high=10, size=(5,2))

array([[9, 9],
       [7, 3],
       [9, 8],
       [3, 2],
       [6, 5]])

### Element wise operation

In [ ]:
# creating array from list
a = np.array([1,2,3,4,5,])
a


array([1, 2, 3, 4, 5])

In [ ]:
# adding 1 to each element in array
a + 1


array([2, 3, 4, 5, 6])

In [42]:
# multiplying each element in array by 100
a * 100

array([100, 200, 300, 400, 500])

In [45]:
# element wise operationb 
b = (10 + (a * 2)) ** 2 
b

array([144, 196, 256, 324, 400])

In [ ]:
# adding/ some operation two array
a + b


array([145, 198, 259, 328, 405])

In [ ]:
# a